// @ts-check

import {
  assertEnvironment,
  moduleExport
} from '@-xun/symbiote/assets/eslint.config.mjs';

import { createDebugLogger } from 'rejoinder';

const debug = createDebugLogger({ namespace: 'symbiote:config:eslint' });

const config = await moduleExport({
  derivedAliases: getEslintAliases(),
  ...(await assertEnvironment())
});

config.push({
  /* Add custom config here, such as disabling certain rules */
});

export default config;

debug('exported config: %O', config);

function getEslintAliases() {
  // ! These aliases are auto-generated by symbiote. Instead of modifying them
  // ! directly, consider regenerating aliases across the entire project with:
  // ! `npx symbiote project renovate --regenerate-assets --assets-preset ...`
  return [
    ['multiverse+mongo-common:*', './packages/mongo-common/src/*'],
    ['multiverse+mongo-item:*', './packages/mongo-item/src/*'],
    ['multiverse+mongo-schema:*', './packages/mongo-schema/src/*'],
    ['multiverse+mongo-test:*', './packages/mongo-test/src/*'],
    ['multiverse+shared:*', './packages/shared/src/*'],
    ['multiverse+mongo-common', './packages/mongo-common/src/index.ts'],
    ['multiverse+mongo-item', './packages/mongo-item/src/index.ts'],
    ['multiverse+mongo-schema', './packages/mongo-schema/src/index.ts'],
    ['multiverse+mongo-test', './packages/mongo-test/src/index.ts'],
    ['multiverse+shared', './packages/shared/src/index.ts'],
    ['rootverse+mongo-common:*', './packages/mongo-common/*'],
    ['rootverse+mongo-item:*', './packages/mongo-item/*'],
    ['rootverse+mongo-schema:*', './packages/mongo-schema/*'],
    ['rootverse+mongo-test:*', './packages/mongo-test/*'],
    ['rootverse+shared:*', './packages/shared/*'],
    ['rootverse:*', './*'],
    ['universe+mongo-common:*', './packages/mongo-common/src/*'],
    ['universe+mongo-item:*', './packages/mongo-item/src/*'],
    ['universe+mongo-schema:*', './packages/mongo-schema/src/*'],
    ['universe+mongo-test:*', './packages/mongo-test/src/*'],
    ['universe+shared:*', './packages/shared/src/*'],
    ['universe+mongo-common', './packages/mongo-common/src/index.ts'],
    ['universe+mongo-item', './packages/mongo-item/src/index.ts'],
    ['universe+mongo-schema', './packages/mongo-schema/src/index.ts'],
    ['universe+mongo-test', './packages/mongo-test/src/index.ts'],
    ['universe+shared', './packages/shared/src/index.ts'],
    ['universe:*', './src/*'],
    ['universe', './src/index.ts'],
    ['testverse+mongo-common:*', './packages/mongo-common/test/*'],
    ['testverse+mongo-item:*', './packages/mongo-item/test/*'],
    ['testverse+mongo-schema:*', './packages/mongo-schema/test/*'],
    ['testverse+mongo-test:*', './packages/mongo-test/test/*'],
    ['testverse+shared:*', './packages/shared/test/*'],
    ['testverse:*', './test/*'],
    ['typeverse:*', './types/*']
  ];
}
