// @ts-check
'use strict';

import { deepMergeConfig } from '@-xun/symbiote/assets';
import { assertEnvironment, moduleExport } from '@-xun/symbiote/assets/jest.config.mjs';
import { createDebugLogger } from 'rejoinder';

const debug = createDebugLogger({ namespace: 'symbiote:config:jest' });

const config = deepMergeConfig(
  moduleExport({ derivedAliases: getJestAliases(), ...assertEnvironment() }),
  {
    // Any custom configs here will be deep merged with moduleExport's result
  }
);

export default config;

debug('exported config: %O', config);

function getJestAliases() {
  const extension = process.env.SYMBIOTE_TEST_JEST_TRANSPILED ? 'js' : 'ts';

  // ! These aliases are auto-generated by symbiote. Instead of modifying them
  // ! directly, consider regenerating aliases across the entire project with:
  // ! `npx symbiote project renovate --regenerate-assets --assets-preset ...`
  return {
    '^multiverse\\+mongo\\x2ditem:(.+)$': '<rootDir>/packages/mongo-item/src/$1',
    '^multiverse\\+mongo\\x2dschema:(.+)$': '<rootDir>/packages/mongo-schema/src/$1',
    '^multiverse\\+mongo\\x2dtest:(.+)$': '<rootDir>/packages/mongo-test/src/$1',
    '^multiverse\\+shared:(.+)$': '<rootDir>/packages/shared/src/$1',
    '^multiverse\\+mongo\\x2ditem$': `<rootDir>/packages/mongo-item/src/index.${extension}`,
    '^multiverse\\+mongo\\x2dschema$': `<rootDir>/packages/mongo-schema/src/index.${extension}`,
    '^multiverse\\+mongo\\x2dtest$': `<rootDir>/packages/mongo-test/src/index.${extension}`,
    '^multiverse\\+shared$': `<rootDir>/packages/shared/src/index.${extension}`,
    '^universe\\+mongo\\x2ditem:(.+)$': '<rootDir>/packages/mongo-item/src/$1',
    '^universe\\+mongo\\x2dschema:(.+)$': '<rootDir>/packages/mongo-schema/src/$1',
    '^universe\\+mongo\\x2dtest:(.+)$': '<rootDir>/packages/mongo-test/src/$1',
    '^universe\\+shared:(.+)$': '<rootDir>/packages/shared/src/$1',
    '^universe\\+mongo\\x2ditem$': `<rootDir>/packages/mongo-item/src/index.${extension}`,
    '^universe\\+mongo\\x2dschema$': `<rootDir>/packages/mongo-schema/src/index.${extension}`,
    '^universe\\+mongo\\x2dtest$': `<rootDir>/packages/mongo-test/src/index.${extension}`,
    '^universe\\+shared$': `<rootDir>/packages/shared/src/index.${extension}`,
    '^universe:(.+)$': '<rootDir>/src/$1',
    '^universe$': `<rootDir>/src/index.${extension}`,
    '^testverse\\+mongo\\x2ditem:(.+)$': '<rootDir>/packages/mongo-item/test/$1',
    '^testverse\\+mongo\\x2dschema:(.+)$': '<rootDir>/packages/mongo-schema/test/$1',
    '^testverse\\+mongo\\x2dtest:(.+)$': '<rootDir>/packages/mongo-test/test/$1',
    '^testverse\\+shared:(.+)$': '<rootDir>/packages/shared/test/$1',
    '^testverse:(.+)$': '<rootDir>/test/$1',
    '^typeverse:(.+)$': '<rootDir>/types/$1',
    '^rootverse\\+mongo\\x2ditem:(.+)$': '<rootDir>/packages/mongo-item/$1',
    '^rootverse\\+mongo\\x2dschema:(.+)$': '<rootDir>/packages/mongo-schema/$1',
    '^rootverse\\+mongo\\x2dtest:(.+)$': '<rootDir>/packages/mongo-test/$1',
    '^rootverse\\+shared:(.+)$': '<rootDir>/packages/shared/$1',
    '^rootverse:(.+)$': '<rootDir>/$1'
  };
}
